name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag v1:$(date +%s)

    - uses: docker/login-action
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Push
      uses: docker/build-push-action@v3
      # run: docker push andrewf2020/proteinscrape:v1
      with:
        push: true
        tags: andrewf2020/proteinscrape:latest
